### ISSUE TITLE
You Get What You See!

### ISSUE THREAD

**Issue by nort3x** [tomowatt/unity-docker-example#1]
it's unity docker example! but it assume you get the webgl folder magically from somewhere....!
i'm not a unity expert and i'm searching for a way to actually build the output , this repository is just an example of how to publish using nginx , it's not unity docker example it's nginx

**Comment by tomowatt** [comment]
@nort3x apologies for any confusion, I worked on this a while ago so it was pretty hastily done/amateur. In terms of the WebGL folder mentioned, that's the Build output from Unity - I named it 'webgl' for ease.

But this was done as a part of an article I wrote, which might give you some more of my though process regarding this code -> https://dev.to/tomowatt/running-an-unity-webgl-game-within-docker-5039

But if not, let me know and we can work something out.
